language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=1
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=1
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=1
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=1
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=1
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=0
  - WP_VERSION=3.8 WP_MULTISITE=0
  - WP_VERSION=3.7 WP_MULTISITE=0
  - WP_VERSION=3.6 WP_MULTISITE=0
  - WP_VERSION=3.5 WP_MULTISITE=0

matrix:
  fast_finish: true
  allow_failures:
    - env: WP_VERSION=3.9 WP_MULTISITE=0
    - env: WP_VERSION=3.8 WP_MULTISITE=0
    - env: WP_VERSION=3.7 WP_MULTISITE=0
    - env: WP_VERSION=3.6 WP_MULTISITE=0
    - env: WP_VERSION=3.5 WP_MULTISITE=0
    - env: WP_VERSION=3.4 WP_MULTISITE=0
    - php: 7
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 7
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: 7
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 7
      env: WP_VERSION=4.2 WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  # disable WP_DEBUG for PHP >= 5.5 due to ext/mysqli E_DEPRECATED errors
  - if [[ "$TRAVIS_PHP_VERSION" > 5.4* ]] && [[ "$WP_VERSION" == "3.6" ]] ; then sed -i "s:define( 'WP_DEBUG://define( 'WP_DEBUG:" /tmp/wordpress-tests-lib/wp-tests-config.php; fi;
  - if [[ "$TRAVIS_PHP_VERSION" > 5.4* ]] && [[ "$WP_VERSION" == "3.7" ]] ; then sed -i "s:define( 'WP_DEBUG://define( 'WP_DEBUG:" /tmp/wordpress-tests-lib/wp-tests-config.php; fi;

script: phpunit
